site_name: Qihang's Notes

site_url: https://qihang-zhang.github.io/notes/

repo_url: https://github.com/Qihang-Zhang/notes
repo_name: Qihang-Zhang/notes

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://qihang-zhang.github.io/notes/
  tags:
    HTML5: html
    JavaScript: js
    CSS: css

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true  

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - blog:
      blog_dir: PaperReading
      blog_toc: true
      post_dir: "{blog}/Papers"
      post_date_format: medium
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      # authors: true
      authors_file: "{blog}/.authors.yml"
      draft: true
      draft_if_future_date: true
  - tags
  - info:
      enabled: false
      enabled_on_serve: true
      archive: false
      archive_stop_on_violation: false
  - offline
  # - offline:
  #     enabled: !ENV [OFFLINE, false]

theme:
  name: material
  features:
    - katex
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
  language: en
  logo: assets/fruit/watermelon.svg
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
  favicon: assets/fruit/lemon.svg


  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

nav: 
  - Homepage: index.md
  - Books: 
    - About: Books/About.md
  - Courses: 
    - EECE 566: 
      - Midterm: 
        - Concept Summary: Courses/EECE 566/Midterm/Concept Summary.md
    - About: Courses/About.md
  - PaperReading: 
    - index: PaperReading/index.md
  - Developing Tools: 
    - Library: 
      - MkDocs: 
        - About: Developing Tools/Library/MkDocs/About.md
      - Pytorch: 
        - About: Developing Tools/Library/Pytorch/About.md
      - Git: 
        - Git-All-In-One: Developing Tools/Library/Git/Git-All-In-One.md
    - Language: 
      - Markdown HTML5 CSS: 
        - About: Developing Tools/Language/Markdown HTML5 CSS/About.md
      - Python: 
        - About: Developing Tools/Language/Python/About.md
      - Shell: 
        - About: Developing Tools/Language/Shell/About.md
      - LaTex: 
        - About: Developing Tools/Language/LaTex/About.md
    - Linux: 
      - About: Developing Tools/Linux/About.md
    - About: Developing Tools/About.md
