# .github/workflows/receive-update.yml
name: update_content

on:
  # monitor the event from the central repo
  repository_dispatch:
    types: [update_repo]
  # can be triggered manually
  workflow_dispatch:

# set the default permissions for the workflow
permissions:
  contents: write # need write permission to commit and push changes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout the edge repo, which is the repo we will modify
      - name: Checkout Edge Repo (self)
        uses: actions/checkout@v4

      # step 2: checkout the central repo
      - name: Checkout Central Logic Repo
        uses: actions/checkout@v4
        with:
          repository: 'Qihang-Zhang/Polyrhythm' # your central repo name
          ref: 'main' # suggest to point to a stable tag, like v1.0.0, to avoid being affected by the main branch development
          token: ${{ secrets.POLYRHYTHM_READ_TOKEN }} # need a PAT to read the central private repo
          path: './central-logic' # download the central repo logic to this subdirectory

      # step 3: prepare env for batch or single mode based on payload
      - name: Prepare sync env (batch-aware)
        run: |
          set -euo pipefail
          pairs=$(jq -c '.client_payload? // {} | .pairs // empty' "$GITHUB_EVENT_PATH" || true)
          if [ -n "$pairs" ]; then
            echo "Detected batch payload with pairs"
            echo "SYNC_PAIRS_JSON=$pairs" >> "$GITHUB_ENV"
          else
            echo "Batch payload not found; falling back to single mapping"
            echo "SYNC_SOURCE_DIR=${{ github.event.client_payload.source_dir }}" >> "$GITHUB_ENV"
            echo "SYNC_TARGET_DIR=${{ github.event.client_payload.target_dir }}" >> "$GITHUB_ENV"
          fi

      # step 4: run the sync script
      - name: Run Sync Script
        env:
          SYNC_SOURCE_REPO: ${{ github.event.client_payload.source_repo }}
          SYNC_SOURCE_REF: ${{ github.event.client_payload.source_ref }}
          CORE_REPO_TOKEN: ${{ secrets.POLYRHYTHM_READ_TOKEN }}
        run: |
          bash ./central-logic/scripts/sync-files.sh

      - name: Clean up temporary logic directory
        if: always() 
        run: rm -rf ./central-logic
